name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  REGISTRY: 'registry.digitalocean.com/mangobot'
  IMAGE_NAME: 'katchup_be'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to DigitalOcean droplet
        uses: appleboy/ssh-action@master
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          GITHUB_SHA: $GITHUB_SHA

          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
          CHATBOT_TOKEN: ${{ secrets.CHATBOT_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          username: ${{ secrets.SSH_USERNAME }}
          envs: IMAGE_NAME,REGISTRY,DIGITALOCEAN_TOKEN,GITHUB_SHA,DATABASE_URL,SECRET_TOKEN,GOOGLE_KEY,CHATBOT_TOKEN,SUPABASE_URL,SUPABASE_ANON_KEY
          script: |
            # Login to registry
            docker login -u $(echo $DIGITALOCEAN_TOKEN) -p $(echo $DIGITALOCEAN_TOKEN) registry.digitalocean.com
            # Stop running container
            docker stop $(echo $IMAGE_NAME)
            # Remove old container
            docker rm $(echo $IMAGE_NAME)
            # Run a new container from a new image
            docker run -d \
            -e DATABASE_URL=$(echo $DATABASE_URL) \
            -e SECRET_TOKEN=$(echo $SECRET_TOKEN) \
            -e GOOGLE_KEY=$(echo $GOOGLE_KEY) \
            -e CHATBOT_TOKEN=$(echo $CHATBOT_TOKEN) \
            -e SUPABASE_URL=$(echo $SUPABASE_URL) \
            -e SUPABASE_ANON_KEY=$(echo $SUPABASE_ANON_KEY) \
            --restart always \
            --name $(echo $IMAGE_NAME) \
            $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
